### PR TITLE
Disable pagespeed v2

### PR DESCRIPTION
**Pull request by hlbraddock**
As per https://www.modpagespeed.com/doc/configuration

### CODE REVIEW

**Review by cru-Luis-Rodriguez — APPROVED** [review]

**Comment by cru-Luis-Rodriguez** [comment]
@hlbraddock 
Did you see the warning? 

```
Warning: do not set ngx_pagespeed to unplugged in 1.12.34.1 and earlier. That will result in crashes. With those versions, use off instead of unplugged.
```

**Comment by cru-Luis-Rodriguez** [comment]
@Omicron7 is there a way to determine the version of pagespeed installed?

**Comment by Omicron7** [comment]
@cru-Luis-Rodriguez https://github.com/CruGlobal/cruorg_proxy/blob/master/Dockerfile#L28

**Comment by cru-Luis-Rodriguez** [comment]
@Omicron7 Thanks -- Setting the module to unplugged should be fine. Just wanted to confirm.

**Comment by Omicron7** [comment]
Test it in stage, maybe?

**Comment by Omicron7** [comment]
nvm, you are. If ultimately we don't re-enable it, we can pull it out of the container and use `apline` linux with very basic openresty.

**Pull request merged**
